### ISSUE TITLE
Handle touch devices

### ISSUE THREAD

**Issue by davidtheclark** [kentor/react-click-outside#4]
I would like to use this component but need it to handle touch events. This would add some code but increase the value. Essentially, I think we'd need to listen for adapt code from https://github.com/alexgibson/tap.js to listen for touchstart, determine whether the action is a scroll or a "tap", and respond to taps.

Are you open to a PR attempting to implement this?

**Comment by mech** [comment]
This is much needed!

**Comment by frontenddeveloping** [comment]
-1

I think developers for major mobile browser vendors don't need touch events since click event can work without delay. To remove the 300-350ms tap delay, all you need is the following in the <head> of your page:
```
<meta name="viewport" content="width=device-width">
```

Works fine on Android (stock, chrome, opera, firefox) browsers, iOS 9+

**Comment by kentor** [comment]
Thanks for the info @frontenddeveloping. 

My inclination is that mobile user agents should interpret taps as clicks natively which is why I'm hesitant to add a userland implementation for detecting taps.

It turns out that, at least from my testing on mobile safari, the click event won't trigger if the element does not have `cursor: pointer`. We can add that to <body> (only on touch devices, otherwise that would be ugly) as a temporary work around.

I'm trying to figure out ways to get ios to register taps as clicks without `cursor: pointer`. If I can't find a better solution then I'll look inside implementing tap detection.

**Comment by oyeanuj** [comment]
@davidtheclark What solution did you end up with for supporting touch devices?

**Comment by oyeanuj** [comment]
@davidtheclark What solution did you end up with for supporting touch devices?

@kentor Any updates on how you are thinking about this now?

**Comment by davidtheclark** [comment]
@oyeanuj I use https://github.com/davidtheclark/teeny-tap.

**Comment by kentor** [comment]
@davidtheclark did you have to update `componentDidMount` and `componentWillUnmount` to use teeny-tap?

**Comment by davidtheclark** [comment]
@kentor Yeah, that's the idea.

**Comment by kentor** [comment]
Since there isn't really a standard on what a "tap" is and I don't want to be opinionated on what constitutes as a tap, and I don't want to add that code to the library, I'll just added a note on the `cursor: pointer` on `<body>` workaround in the README.

Another option is to provide an extension point for using something other than `document.addEventListener('click', ...)` to trigger the callback. Let me know if that is desired.
